@startuml
participant Клиент
boundary    Сайт
control     Сервис_формирования_задач
control     Сервис_распределения
control     Сервис_мониторинга
database     База_данных
boundary     Prometheus
control     Node_N
autonumber
Сервис_мониторинга -> Сервис_мониторинга++ : Проверять\nсостояние\nсерверов
Клиент -> Сайт++ : Выбрать параметры
Сайт -> Сервис_формирования_задач++ : Отправить заданные параметры
Сервис_формирования_задач -> Сервис_распределения++ : Получить доступную машину
Сервис_распределения -> Prometheus++ : Получить данные по всем машинам
Prometheus -> Сервис_распределения-- : Вернуть данные о загрузке серверов
Сервис_распределения -> Сервис_распределения : Выбрать машину
Сервис_распределения -> Сервис_формирования_задач-- : Вернуть доступную машину
Сервис_формирования_задач -> Node_N++ : Отправить задачу
Node_N -> Сервис_формирования_задач : Сообщить о начале работы
Сервис_формирования_задач -> База_данных++ : Сохранить данные о задаче
База_данных -> Сервис_формирования_задач-- : Данные сохранены
Сервис_формирования_задач -> Сайт-- : Сообщить номер сервера
Сайт -> Клиент-- : Сообщить номер сервера
Сервис_мониторинга -> Prometheus++ : Получить данные по всем машинам
Prometheus -> Сервис_мониторинга-- : Вернуть данные о состоянии серверов
Сервис_мониторинга -> Сервис_формирования_задач++ : Машина N вышла из строя
Сервис_формирования_задач -> База_данных++ : Получить данные о задаче
База_данных -> Сервис_формирования_задач-- : Данные о задаче
Сервис_формирования_задач -> Сервис_распределения++ : Получить доступную машину (См. пункт 4)

@enduml